const VOCATIVE = 'VOCATIVE'
const PREDICATE = 'PREDICATE'
const COMPLEMENT = 'COMPLEMENT'
const SUBJECT = 'SUBJECT'
const INFINITIVE = 'INFINITIVE'
const DIRECT_OBJECT = 'DIRECT_OBJECT'
const PREPOSITIONAL_OBJECT = 'PREPOSITIONAL_OBJECT'
const NEGATIVE = 'NEGATIVE'
const INTERROGATIVE = 'INTERROGATIVE'
const INTERROGATIVE_REPETITION = 'INTERROGATIVE_REPETITION'
const VOCATIVE_PARTICLE = 'VOCATIVE_PARTICLE'
const INDICATIVE_PARTICLE = 'INDICATIVE_PARTICLE'
const OPTATIVE_PARTICLE = 'OPTATIVE_PARTICLE'
const DIRECT_OBJECT_PARTICLE = 'DIRECT_OBJECT_PARTICLE'
const COMPOUND_COMPLEMENT_PARTICLE = 'COMPOUND_COMPLEMENT_PARTICLE'
const AND_PARTICLE = 'AND_PARTICLE'
const OR_PARTICLE = 'OR_PARTICLE'
const CONTEXT_PARTICLE = 'CONTEXT_PARTICLE'
const CONTEXT_SUBJECT = 'CONTEXT_SUBJECT'
const CONTEXT_PREDICATE = 'CONTEXT_PREDICATE'

module.exports = {
  VOCATIVE: VOCATIVE,
  PREDICATE: PREDICATE,
  COMPLEMENT: COMPLEMENT,
  SUBJECT: SUBJECT,
  INFINITIVE: INFINITIVE,
  DIRECT_OBJECT: DIRECT_OBJECT,
  PREPOSITIONAL_OBJECT: PREPOSITIONAL_OBJECT,
  NEGATIVE: NEGATIVE,
  INTERROGATIVE: INTERROGATIVE,
  INTERROGATIVE_REPETITION: INTERROGATIVE_REPETITION,
  VOCATIVE_PARTICLE: VOCATIVE_PARTICLE,
  INDICATIVE_PARTICLE: INDICATIVE_PARTICLE,
  OPTATIVE_PARTICLE: OPTATIVE_PARTICLE,
  DIRECT_OBJECT_PARTICLE: DIRECT_OBJECT_PARTICLE,
  COMPOUND_COMPLEMENT_PARTICLE: COMPOUND_COMPLEMENT_PARTICLE,
  AND_PARTICLE: AND_PARTICLE,
  OR_PARTICLE: OR_PARTICLE,
  CONTEXT_PARTICLE: CONTEXT_PARTICLE,
  CONTEXT_SUBJECT: CONTEXT_SUBJECT,
  CONTEXT_PREDICATE: CONTEXT_PREDICATE,
}
